export type TCurrency = "CAD" |
                        "HKD" |
                        "ISK" |
                        "PHP" |
                        "DKK" |
                        "HUF" |
                        "CZK" |
                        "GBP" |
                        "RON" |
                        "SEK" |
                        "IDR" |
                        "INR" |
                        "BRL" |
                        "RUB" |
                        "HRK" |
                        "JPY" |
                        "THB" |
                        "CHF" |
                        "EUR" |
                        "MYR" |
                        "BGN" |
                        "TRY" |
                        "CNY" |
                        "NOH" |
                        "NZD" |
                        "ZAR" |
                        "USD" |
                        "MXN" |
                        "SGD" |
                        "AUD" |
                        "ILS" |
                        "KRW" |
                        "PLN"